version: '3'

services:
    apache:
        container_name: ${COMPOSE_PROJECT_NAME}_apache
        build:
            context: ./apache
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - WEB_FOLDER=${WEB_FOLDER}
                - APACHE_SSL_EXPOSED_PORT=${APACHE_SSL_EXPOSED_PORT}
                - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
                - PHP_FPM_PORT=${PHP_FPM_PORT}
        links:
            - php-fpm:php-fpm
        volumes:
            - ../logs/apache:/var/log/apache2
            - ../html:${WEB_FOLDER}
        ports:
            - ${APACHE_EXPOSED_PORT}:80
            - ${APACHE_SSL_EXPOSED_PORT}:443
        environment:
            - APACHE_SSL_EXPOSED_PORT=${APACHE_SSL_EXPOSED_PORT}
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
    php-fpm:
        container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
        build:
            context: ./php-fpm
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - PHP_ROOT_DIR=${PHP_ROOT_DIR}
                - PHP_FPM_PORT=${PHP_FPM_PORT}
        volumes:
            - ../html:${WEB_FOLDER}
            - ../logs/php:${PHP_ROOT_DIR}/logs
        environment:
            - PHP_ROOT_DIR=${PHP_ROOT_DIR}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
